[2022-12-04 16:23:39,018] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.call_dataset_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:23:39,029] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.call_dataset_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:23:39,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:23:39,030] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 16:23:39,030] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:23:39,042] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): call_dataset_task> on 2022-12-03 00:00:00+00:00
[2022-12-04 16:23:39,048] {standard_task_runner.py:52} INFO - Started process 1026 to run task
[2022-12-04 16:23:39,052] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingest_yuda', 'call_dataset_task', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_yuda.py', '--cfg-path', '/tmp/tmp__m738k0', '--error-file', '/tmp/tmp_wqhspvj']
[2022-12-04 16:23:39,053] {standard_task_runner.py:77} INFO - Job 3: Subtask call_dataset_task
[2022-12-04 16:23:39,106] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingest_yuda.call_dataset_task scheduled__2022-12-03T00:00:00+00:00 [running]> on host 73a87de6132e
[2022-12-04 16:23:39,158] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yudasatrias
AIRFLOW_CTX_DAG_ID=data_ingest_yuda
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04 16:23:39,598] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 16:23:39,609] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingest_yuda, task_id=call_dataset_task, execution_date=20221203T000000, start_date=20221204T162339, end_date=20221204T162339
[2022-12-04 16:23:39,866] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 16:23:39,905] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
